services:
  frontend:
    container_name: clubhub-web_frontend
    build:
      context: ./clubhub-web
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: always
    env_file:
      - ./clubhub-web/.env
