name: Build and Deploy Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Docker Compose (Detached)
        run: docker compose up -d

      - name: "Mock: Run E2E Tests"
        run: |
          echo "Running E2E tests..."
          sleep 3
          echo "Tests passed!"

      - name: Tag and Push Docker Image
        run: |
          # Delete all version images except latest
          docker images ${{ secrets.DOCKER_USERNAME }}/clubhub --format "table {{.Tag}}" | grep -v "latest" | grep -v "TAG" | xargs -I {} docker rmi ${{ secrets.DOCKER_USERNAME }}/clubhub:{} || true
          # Tag and push new version
          docker tag clubhub-web_frontend ${{ secrets.DOCKER_USERNAME }}/clubhub:${{ github.ref_name }}
          docker push ${{ secrets.DOCKER_USERNAME }}/clubhub:${{ github.ref_name }}

      - name: Tear Down Docker Containers
        run: docker compose down

      - name: Create and Auto-Merge PR into Develop
        uses: peter-evans/create-pull-request@v7
        with:
          base: develop
          branch: release/${{ github.ref_name }}
          title: "Release ${{ github.ref_name }} → develop"
          body: "Auto-generated PR after successful Docker image deployment."
          delete-branch: true
          merge: true