name: Nightly Instagram Scraper

on:
  schedule:
    - cron: '10 4 * * *'  # 12:10 AM EDT / 11:10 PM EST
  workflow_dispatch: # Allow manual triggering
  push:
    branches:
      - deployment

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: deployment
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.5'
      
    - name: Make execute.sh executable
      run: chmod +x execute.sh
      working-directory: ./clubhub-bot
      
    - name: Run execute.sh script
      env:
        APIFY_KEY_1: ${{ secrets.APIFY_KEY_1 }}
        APIFY_KEY_2: ${{ secrets.APIFY_KEY_2 }}
        APIFY_KEY_3: ${{ secrets.APIFY_KEY_3 }}
        APIFY_KEY_4: ${{ secrets.APIFY_KEY_4 }}
        APIFY_KEY_5: ${{ secrets.APIFY_KEY_5 }}
        APIFY_KEY_6: ${{ secrets.APIFY_KEY_6 }}
        APIFY_KEY_7: ${{ secrets.APIFY_KEY_7 }}
        APIFY_KEY_8: ${{ secrets.APIFY_KEY_8 }}
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        ADMIN_FIREBASE_PROJECT_ID: ${{ secrets.ADMIN_FIREBASE_PROJECT_ID }}
        ADMIN_FIREBASE_PRIVATE_KEY: ${{ secrets.ADMIN_FIREBASE_PRIVATE_KEY }}
        ADMIN_FIREBASE_CLIENT_EMAIL: ${{ secrets.ADMIN_FIREBASE_CLIENT_EMAIL }}
      run: ./execute.sh
      working-directory: ./clubhub-bot
